export type League = "college-football" 
    | "nba"
    | "wnba"
    | "nhl" 
    | "mens-college-basketball" 
    | "womens-college-basketball"
    | "nfl" 
    | "mlb" 
    | "arg.1"
    | "eng.1"
    | "usa.1"
    | "fra.1"
    | "esp.1"
    | "ned.1"
    | "ita.1"
    | "mex.1"
    | "bra.1"
    | "por.1";